# -*- coding: utf-8 -*-
"""Tweets_Word2Vec

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19s2rn-Q9Fd_wCESiik6Yp5vBXpS6_rw_
"""

!pip install gensim
from gensim.models import Word2Vec
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import re
import pickle

import gensim.downloader

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('Tweets.csv')
df.head()

df = df[['text','airline_sentiment']]

df.isnull().sum()

df.duplicated().sum()

df.dropna(inplace=True)

df.reset_index(drop=True,inplace=True)

def clean_text(text):

    text = text.lower()

    text = re.sub(r"http\S+"," ",text)

    text = re.sub(r"@\w+"," @ ",text)

    text = re.sub(r"[^a-z@ ]"," ",text)

    text = re.sub(r"\s+"," ",text).strip()

    return text.split()

# Apply preprocessing
sentences = df["text"].fillna("").apply(clean_text)

word2vec_model = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

print("Vocabulary Size:", len(word2vec_model.wv))

"""## Convert Each Tweet into a Feature Vector"""

def get_sentence_vector(sentence):
    vectors = [word2vec_model.wv[word] for word in sentence if word in word2vec_model.wv]

    if len(vectors) == 0:
        return np.zeros(word2vec_model.vector_size)

    return np.mean(vectors, axis=0)

# Create Word2Vec feature matrix
X = np.array([get_sentence_vector(sentence) for sentence in sentences])

print("Feature Matrix Shape:", X.shape)

for i in range(10):
    print(f"Original Tweet {i+1}:")
    print(df['text'][i])
    print("\nCleaned Tweet:")
    print(sentences.iloc[i])
    print("-" * 80)

vector = word2vec_model.wv['said']
print(vector)
print(len(vector))

"""## Prepare Labels"""

y = df["airline_sentiment"]

print(y.value_counts())

"""## Encode Labels"""

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

print(encoder.classes_)

"""## Split the Dataset"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

"""## Random Forest"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

"""## Support Vector Machine"""

from sklearn.svm import SVC
svm = SVC()

svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)
print(y_pred)

acc= accuracy_score(y_test, y_pred)
print("Accuracy Score:", acc)

"""## Logistic Regression"""

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print(y_pred)

acc= accuracy_score(y_test, y_pred)
print("Accuracy Score:", acc)

"""## Gradient Boosting"""

from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state=42)

gb.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print(y_pred)

acc= accuracy_score(y_test, y_pred)
print("Accuracy Score:", acc)

"""## Artifical Neural Networks (ANN)"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential()

# Input layer + Hidden Layer 1
model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.3))

# Hidden Layer 2
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))

# Hidden Layer 3
model.add(Dense(32, activation='relu'))

# Output layer (3 sentiment classes)
model.add(Dense(3, activation='softmax'))

model.summary()

"""## Compile the Model"""

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

"""### One-Hot Encode Labels for ANN"""

from tensorflow.keras.utils import to_categorical

# Determine the number of classes from the encoder
num_classes = len(encoder.classes_)

# Convert integer labels to one-hot encoded labels
y_train_one_hot = to_categorical(y_train, num_classes=num_classes)
y_test_one_hot = to_categorical(y_test, num_classes=num_classes)

print("Shape of y_train_one_hot:", y_train_one_hot.shape)
print("Shape of y_test_one_hot:", y_test_one_hot.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# Re-define the model to ensure a fresh state
model = Sequential()

# Input layer + Hidden Layer 1
model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.3))

# Hidden Layer 2
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))

# Hidden Layer 3
model.add(Dense(32, activation='relu'))

# Output layer (3 sentiment classes)
model.add(Dense(3, activation='softmax'))

model.summary()

# Re-compile the model to ensure a fresh state
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train_one_hot, # Use the correct one-hot encoded labels
    validation_data=(X_test, y_test_one_hot), # Use the correct one-hot encoded labels
    epochs=20,
    batch_size=32,
    verbose=1
)

loss, accuracy = model.evaluate(X_test, y_test_one_hot)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

import numpy as np
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test_one_hot, axis=1) # Corrected variable name

print(classification_report(y_true, y_pred_classes))

model.save("sentiment_model.keras")

with open("label_encoder.pkl", "wb") as f:
    pickle.dump(encoder, f)

scaler = StandardScaler()
scaler.fit(X_train)
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

embedding_lookup = {word: word2vec_model.wv[word] for word in word2vec_model.wv.index_to_key}
with open("embedding_lookup.pkl", "wb") as f:
    pickle.dump(embedding_lookup, f)

from google.colab import files
files.download("sentiment_model.keras")
files.download("label_encoder.pkl")
files.download("scaler.pkl")
files.download("embedding_lookup.pkl")

